version: '3.7'
services:
  db:
      image: mariadb
      environment:
        MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3307:3306"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: unless-stopped

#docker-compose up --build -d
